### ISSUE TITLE
incomplete normalization?

### ISSUE THREAD

**Issue by josejhlee** [azshue/AdvBN#1]
Hi authors,
Is the standard deviation missing when normalizing the natural features?
Thank you!

https://github.com/azshue/AdvBN/blob/7f9283d1383603d4298ecf7d4133a316362f0744/train_imagenet.py#L384

**Comment by azshue** [comment]
Hi,

Thank you for your interest in our work. 

This indeed looks a bit confusing, but it's a simplified formula of AdvBN: Since AdvBN "rescales" both the mean and std dev, the original std dev term will cancel out. (See Eq.(1) in [our paper](https://arxiv.org/pdf/2009.08965.pdf)).

And back to the code, the `new_std` term in [this line](https://github.com/azshue/AdvBN/blob/7f9283d1383603d4298ecf7d4133a316362f0744/train_imagenet.py#L395) is the actually scaling factor ($\delta'_{\sigma}$ in Eq.(1)) of the original std dev. If we do a "full" normalization in #L384, then we'll multiply `ori_std` back in this line.

I hope this answers your question for you. Let me know if there are any other questions!
